### ISSUE TITLE
CircleCI2.0に対応させる

### ISSUE THREAD

**Issue by kurochan** [ictsc/ictsc-github-member#98]
もうすぐCircleCI1.0が終了する

**Comment by whywaita** [comment]
> This project is currently running on CircleCI 1.0 which will no longer be supported after August 31, 2018. Please start migrating this project to CircleCI 2.0.

:eyes:

**Comment by h-otter** [comment]
多分完了した認識

良さそうであればクローズお願いします 🙏

**Comment by kurochan** [comment]
ありがとうー！
